name: example
description: Charts-Flutter Demo
environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  charts_flutter_custom:
    path: ../
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  meta: ^1.9.1
  intl: ^0.18.0
flutter:
  uses-material-design: true
