name: charts_flutter_custom
version: 0.12.2
description: Material Design charting library for flutter.
homepage: https://github.com/enoquemaculuba/flutter_charts.git
publish_to: none

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  # Pointing this to a local path allows for pointing to the latest code
  # in Github for open source development.
  #
  # The pub version of charts_flutter will point to the pub version of charts_common.
  # The latest pub version is commented out and shown below as an example.
  #charts_common_custom: ^0.12.2
  charts_common_custom:
     git:
       url: https://github.com/enoquemaculuba/flutter_charts.git
       ref: master
       path: charts_common_custom
  collection: ^1.17.0
  flutter:
    sdk: flutter
  intl: ^0.18.0
  logging: ^1.1.1
  meta: ^1.9.1

dev_dependencies:
  mockito: ^5.4.0
  build_runner: ^2.3.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  test: ^1.21.4
